name: Validate Citations File

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - 'CITATION.cff'
      - '.github/workflows/validate-citations-file.yml'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'CITATION.cff'
      - '.github/workflows/validate-citations-file.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  validate:
    name: Validate Citations File
    uses: the-lupaxa-project/workflows/.github/workflows/reusable-validate-citations-file.yml@master
    secrets: inherit

  generate-workflow-summary:
    name: Generate Workflow Summary
    needs:
      - validate
    if: always()
    uses: the-lupaxa-project/workflows/.github/workflows/reusable-workflow-summary.yml@master

  generate-workflow-notifications:
    name: Generate Workflow Notifications
    needs:
      - generate-workflow-summary
    if: always()
    uses: the-lupaxa-project/workflows/.github/workflows/reusable-workflow-notifier.yml@master
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
